name: Test Demo Action
on:
  workflow_dispatch:

jobs:
  test_zarifs_action:
    runs-on: ubuntu-latest
    steps:
      - uses: zarifaziz/hello-world-github-action@v1.0.0
        with:
          person: 'Maple'
